import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile(new URL("../index.html", import.meta.url), "utf8");

assert.match(html, /brewBakeLab\.coffeeBeans\.v1/);
assert.match(html, /data-page="beans"><i data-lucide="coffee"><\/i>咖啡豆仓库/);
assert.match(html, /function getBeanComponents\(bean\)/);
assert.match(html, /data-bean-variety/);
assert.match(html, /data-bean-process/);
assert.match(html, /data-bean-ratio/);
assert.match(html, /if \(rows\.length <= 1\)/);
assert.match(html, /\.bean-card strong \{ grid-column: 1; grid-row: 1;/);
assert.match(html, /\.bean-card span \{ grid-column: 1; grid-row: 2;/);
assert.match(html, /\.bean-card > svg \{ grid-row: 1 \/ 3; grid-column: 2;/);
assert.match(html, /id="beanDetail"/);
assert.match(html, /function renderBeanDetail\(beanId\)/);
assert.match(html, /function getBeanBrewParams\(bean\)/);
assert.match(html, /id="beanPourDose"/);
assert.match(html, /id="beanEspressoDose"/);
assert.match(html, /data-open-brew-guide="pour"/);
assert.match(html, /id="brewGuide"/);
assert.match(html, /function renderBrewGuidePage\(beanId, kind = "pour"\)/);
assert.match(html, /data-guide-kind="\$\{escapeHTML\(recipe\.guideKind/);
assert.match(html, /title: "三段式手冲"/);
assert.match(html, /title: "意式浓缩"/);
assert.match(html, /function applyCoffeeTemplate\(recipe, template, coffeeBeanId = ""\)/);
assert.match(html, /function defaultPourPlan\(\)/);
assert.match(html, /function renderPourPlan\(recipe, isEditing = false\)/);
assert.match(html, /id="genericPourPlan"/);
assert.match(html, /function fixedPourPlan\(recipe\)/);
assert.match(html, /recipe\.pourStages = \[/);
assert.match(html, /function renderPourStageParams\(recipe, isEditing = false\)/);
assert.match(html, /coffee-parameter-view/);
assert.match(html, /编辑参数/);
assert.match(html, /data-pour-stage-time/);
assert.match(html, /data-pour-stage-grams/);
assert.match(html, /id="pourPresetSelect"/);
assert.match(html, /id="openPourGuide"/);
assert.match(html, /固定做法，只替换当前参数/);
assert.match(html, /\.bean-editor-dialog/);
assert.match(html, /\.bean-form-scroll/);
assert.doesNotMatch(html, /value="pour-over">手冲参数卡/);
assert.match(html, /function renderGenericBeanLink\(recipe, isEditing = false\)/);
assert.match(html, /if \(recipe\.coffeeBeanId === id\) recipe\.coffeeBeanId = ""/);
assert.match(html, /key\?\.startsWith\("brewBakeLab\."\)/);
assert.match(html, /记录香气、酸甜苦、口感与降温后的变化/);
assert.match(html, /记录甜感、酸苦平衡、醇厚度与下一杯调整/);

console.log("Coffee bean profiles, reusable recipe links, and pour-over/espresso templates are present.");
